name = "kakarot-ai"
compatibility_date = "2024-01-01"
main = "src/index.js"
account_id = "ae693ae9f4faf8d8202a61970309f150"

routes = [
  { pattern = "kakarot-ai.cc.cd/*", zone_id = "2062c1b3a6a38a40d4bf4ac15a3f435a" }
]

# D1 placeholder

[[kv_namespaces]]
binding = "KV"
id = "f8c6e66fd2134f5dbb15384a2578a0d7"

[[r2_buckets]]
binding = "R2"
bucket_name = "kakarot-storage"

[triggers]
crons = ["0 0 * * *", "0 0 1 * *"]

[env.production]
ENVIRONMENT = "production"
APP_URL = "https://kakarot-ai.cc.cd"
PERPLEXITY_API_URL = "https://www.perplexity.ai/rest/sse/perplexity_ask"

[env.development]
ENVIRONMENT = "development"